#' PLot latent effects over time
#'
#' @param posterior_summary `posterior_summary` object generated by `btblv::posterior_summary`.
#' @param highlight character vector with groups to be highlighted on the plot. Default is NULL.
#'
#' @return ggplot graph object
#' @export
#' @importFrom latex2exp TeX
#'
#' @examples
#' # example_fit$specific_K1 |>
#' # extract_posterior() |>
#' # posterior_summary() |>
#' # plot_latent_effects()
#'
plot_latent_effects = function(posterior_summary, highlight = NULL) {

  theta_df = posterior_summary$posterior_summary_df$theta

  group_col_name = names(theta_df)[7]
  time_col_name = names(theta_df)[8]

  names(theta_df)[7:8] = c("group", "time")

  theta_wide = theta_df %>%
    dplyr::select(mean, group, time, K) %>%
    tidyr::spread(K, mean)

  if(!is.null(highlight)) {
    pl = theta_df %>%
      mutate(sel_group = ifelse(group %in% highlight, group, "Others")) %>%
      mutate(sel_alpha = ifelse(sel_group == "Others", "Others", "Sel")) %>%
      mutate(K = paste0("Dimension ", K)) %>%
      ggplot(aes(x=time, y=mean, group=group, color=sel_group, alpha = sel_alpha)) +
      geom_line() +
      geom_hline(yintercept = 0, linetype = "dashed") +
      scale_alpha_manual(values = c(0.16, 1), guide = "none") +
      facet_wrap(K ~ ., scales = "free_y") +
      labs(x=time_col_name,
           y=latex2exp::TeX("$\\theta_{ik}^{(t)}$"),
           color=paste0(group_col_name, ":")) +
      theme(legend.position = "top", text = element_text(size = 9))
  }else{
    pl = theta_df %>%
      mutate(K = paste0("Dimension ", K)) %>%
      ggplot(aes(x=time, y=mean, group=group)) +
      geom_line() +
      geom_hline(yintercept = 0, linetype = "dashed") +
      facet_wrap(K ~ ., scales = "free_y") +
      labs(x=time_col_name,
           y=latex2exp::TeX("$\\theta_{ik}^{(t)}$"),
           color=paste0(group_col_name, ":")) +
      theme(legend.position = "top", text = element_text(size = 9))
  }

  return(pl)
}
